# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Lanes for iOS app"

  lane :tests do
    # add actions here: https://docs.fastlane.tools/actions
    run_tests(scheme: "JenkinsFastlane",
    	devices: "iPhone 6s",
    	slack_url: "https://hooks.slack.com/services/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")
  end

  lane :beta do
  	# increment_build_number(
  	# 	build_number: latest_testflight_build_number + 1,
  	# 	xcodeproj: "JenkinsFastlane.xcodeproj"
  	# )
  	# build_app(scheme: "JenkinsFastlane",
  	# 		include_bitcode: true)
  	upload_to_testflight
  	slack(message: "Successfully upload new build to TestFlight")
  end

end